version: '3.8'

services:
  database:
    container_name: grpcchatter_database
    image: postgres:15
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - grpcchatter_data:/var/lib/postgresql/data
      - ./dbscripts/:/docker-entrypoint-initdb.d/
    networks:
      - grpcchatter_net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: grpcchatter_server
    image: mateuszskowron21/grpcchatter
    restart: on-failure
    networks:
      - grpcchatter_net
    ports:
      - "5050:5050"
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  grpcchatter_data:
    driver: local

networks:
  grpcchatter_net:
    driver: bridge
